# vim: set sw=4 et:
#
# http://borntyping.co.uk/posts/tox-and-travis-ci.html
#

language: python
python:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
install: pip install tox
script: tox

