# vim: set sw=4 et:
#

language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi 
script: python setup.py test

